/** Declaration file generated by dts-gen */

export = l1_path_finder;

declare function l1_path_finder(grid: any): any;

declare namespace l1_path_finder {
    const prototype: {
    };

}

declare module "l1_path_finder";